### ISSUE TITLE
Adding support for robotiq hand-e

### ISSUE THREAD

**Issue by TomCC7** [PickNikRobotics/ros2_robotiq_gripper#51] opened 2024-06-17 18:50 UTC
Hi, I would like to add support for robotiq hand-e to this repo. Is there a standard strategy for adding a new gripper?

**Comment by nbbrooks** [comment] 2024-12-27 22:01
Duplicate of https://github.com/PickNikRobotics/ros2_robotiq_gripper/issues/69 with less traffic

**Closed by nbbrooks** 2024-12-27 22:01 UTC
